const Home = () => {
  return (
    <div>
      <h2>Home Page</h2>
      <p>Welcome to our website!</p>
      <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc et velit arcu. Curabitur consequat urna eget tincidunt rhoncus. Sed ut condimentum velit. Nam at est hendrerit, accumsan leo ut, viverra mi. Mauris quis euismod leo. Pellentesque ornare rhoncus arcu quis viverra. Morbi euismod, ipsum ac fermentum vestibulum, elit neque sodales lectus, vel elementum nunc mauris at odio. Nullam placerat erat sollicitudin blandit tincidunt. Morbi vitae augue eu orci molestie scelerisque rhoncus tincidunt dui. Ut vestibulum, tortor in fringilla condimentum, ipsum justo lobortis nisi, non sodales odio orci sed justo. </p>
      <p> Integer eu justo nulla. Sed in tortor in magna tempor tempor. Maecenas et magna vel massa rhoncus volutpat. Maecenas rhoncus eu arcu consectetur finibus. Aliquam ullamcorper pretium ligula tincidunt hendrerit. Proin pharetra lectus eu laoreet dignissim. Duis in finibus magna, nec dapibus odio. Sed nec ipsum sed magna vehicula placerat. Donec id nulla arcu. </p>
      <p> Ut imperdiet pretium erat vitae fermentum. Nam ut malesuada orci. Donec id euismod libero. Vestibulum accumsan erat quis hendrerit hendrerit. Fusce porttitor fermentum ullamcorper. Nunc faucibus, elit nec lobortis varius, erat nibh porttitor nunc, venenatis fringilla sapien libero vitae turpis. Nulla at sapien lacinia, lacinia diam blandit, tincidunt ipsum. Vivamus convallis, nisl id vehicula eleifend, erat arcu pulvinar est, quis posuere elit turpis a quam. Vestibulum vestibulum lectus rhoncus libero placerat dapibus. Proin congue justo ut quam faucibus ornare. Etiam eget facilisis sem, ac rutrum justo. Sed tristique ante lacus, quis bibendum dui tincidunt at. Fusce ac euismod dolor, vitae hendrerit nibh. Etiam scelerisque diam arcu, ac finibus justo sodales eu. Pellentesque quis urna dui. Integer lorem tellus, lobortis ut interdum ac, maximus volutpat ex. </p>
      <p> Aenean sed imperdiet dolor, accumsan tempus nulla. Sed sapien nibh, pellentesque finibus risus ut, porta vulputate odio. In hac habitasse platea dictumst. Pellentesque in leo nisi. Donec et libero sit amet quam condimentum dictum sit amet ac ipsum. Aliquam tristique consectetur sodales. Proin non sodales turpis. Nulla mauris enim, maximus ut erat in, maximus tincidunt diam. Quisque erat purus, volutpat condimentum lorem id, consectetur imperdiet arcu. Morbi fermentum lobortis felis, a maximus tellus luctus ut. </p>
      <p> Cras convallis ultricies dui vitae consequat. Nunc vel eros convallis, pulvinar massa vel, porttitor tellus. Ut suscipit porta vehicula. Praesent eget vehicula libero, in porttitor dolor. Sed commodo gravida tellus tristique faucibus. Morbi dapibus rutrum lacus, ut luctus metus dapibus nec. Vivamus egestas, odio at viverra vestibulum, odio tellus suscipit lectus, et ultricies justo dui et diam. Curabitur sollicitudin rutrum augue sed mollis. Quisque ac leo convallis, scelerisque enim eget, facilisis elit. Aliquam in felis risus. Cras erat augue, accumsan vel consectetur at, condimentum a dui. Sed tempus eget arcu at pharetra. </p>
      <p> Nullam nisi tortor, ultrices vitae massa sed, auctor aliquam mi. Proin a odio at leo commodo suscipit. Praesent rutrum tellus eu orci sagittis, ac fringilla metus interdum. Fusce a malesuada elit. Donec vel commodo leo. Suspendisse quis fermentum mi. Sed ullamcorper accumsan dui, vitae faucibus ante. </p>
      <p> Etiam vel consequat elit. Ut in justo ac eros elementum tincidunt eget semper ex. Integer tortor mauris, maximus quis hendrerit nec, ultrices cursus arcu. Phasellus et rhoncus elit. Duis hendrerit pulvinar auctor. Duis augue dui, maximus placerat consectetur quis, pretium nec arcu. Nunc a arcu nec nisi placerat commodo. Ut eget orci nisi. Quisque consectetur auctor neque ut tempor. Ut lacus magna, euismod id lobortis a, pharetra pellentesque est. Quisque sed magna laoreet lectus aliquet dignissim eu vitae odio. Proin urna augue, vestibulum eget porta vitae, aliquet quis orci. Etiam congue vestibulum molestie. Phasellus pellentesque quis orci vel volutpat. </p>
      <p> Etiam mattis vitae elit in porttitor. Phasellus massa magna, viverra sed tristique non, sodales sit amet tortor. Integer tristique tellus nec diam dapibus tincidunt. Suspendisse tincidunt ligula ultrices, ullamcorper quam tempor, mattis est. Pellentesque eget dui eros. Cras sapien justo, hendrerit at semper at, sodales interdum orci. In dictum nisl eget erat tristique, nec tincidunt risus vehicula. Nunc non nulla erat. Suspendisse potenti. Mauris nec auctor eros. </p>
      <p> Etiam scelerisque, eros in tincidunt fermentum, diam mi pellentesque ligula, id aliquet ipsum neque in odio. Nunc convallis venenatis semper. Aenean ipsum urna, placerat et tempus eu, egestas sit amet mauris. Quisque at egestas justo, ac euismod enim. Quisque hendrerit et urna porttitor congue. Ut urna urna, pellentesque non ultrices vel, mollis vitae nulla. Ut vel mi ut velit efficitur euismod. Nam ultrices mattis eros hendrerit sagittis. Integer pharetra blandit malesuada. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse et varius dui. Donec tellus neque, pretium quis metus consequat, feugiat lobortis libero. Sed dapibus quam a quam gravida fermentum. </p>
      <p> Sed at aliquam massa. Curabitur vitae sagittis lorem, nec ullamcorper orci. Quisque gravida dignissim varius. Fusce nec sodales arcu, a pretium nisi. Nunc eget nibh mollis, interdum purus non, luctus felis. Pellentesque dictum sagittis neque, ac rhoncus nulla aliquet a. Curabitur vel nibh sapien. Nunc convallis dictum nulla, non fermentum urna suscipit sed. Maecenas scelerisque scelerisque quam, nec faucibus sem sollicitudin ut. Nullam ut massa rutrum, finibus sem id, vulputate ipsum. Phasellus non nisi fermentum, lobortis neque eu, eleifend velit. </p>
      <p> Nullam vel dui ullamcorper mi mattis interdum maximus vitae nunc. Mauris ac dolor metus. Aenean lectus nunc, imperdiet feugiat tincidunt eget, imperdiet et enim. Integer fermentum tincidunt mollis. Vivamus commodo mauris a sollicitudin auctor. Sed congue augue id est tincidunt rhoncus. Nam tincidunt magna ut nisi vehicula, quis ultricies nunc interdum. Aenean finibus vulputate dui, a semper purus accumsan nec. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Phasellus hendrerit neque eu varius luctus. Donec mollis accumsan commodo. Nulla at erat hendrerit, pellentesque arcu vitae, viverra est. </p>
      <p> Vestibulum consectetur a felis in rutrum. Suspendisse lacinia augue ipsum, et lobortis nibh ultricies ac. Vivamus ac ultrices nibh, ut condimentum mauris. Proin sem justo, molestie eget risus vitae, ultrices euismod enim. Integer eros ex, ultrices quis odio non, efficitur congue nunc. Ut ullamcorper eget neque id eleifend. Donec a nisi id dui venenatis efficitur quis eu massa. Nam eu vehicula urna. Donec non nisl neque. </p>
    </div>
  );
};

export default Home;
